apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-jenkins-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-jenkins-demo
  template:
    metadata:
      labels:
        app: go-jenkins-demo
    spec:
      containers:
      - image: waynewu411/go-jenkins-demo:0.0.4
        name: go-jenkins-demo
        ports:
        - containerPort: 8080
        - containerPort: 50050
---
apiVersion: v1
kind: Service
metadata:
  name: go-jenkins-demo
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 50050
    name: grpc
    targetPort: 50050
  selector:
    app: go-jenkins-demo