apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-jenkins-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@k3sdev:wwu/go-jenkins-demo.git'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: go-jenkins-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true