pipeline {

  environment {
    CONTAINER_REGISTRY_CREDENTIALS = credentials('dockerhub')
  }

  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: docker
            image: waynewu411/docker-cli:1.0
            command:
            - cat
            tty: true
            volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
          volumes:
          - name: certs
            secret:
                secretName: buildkit-client-certs
        '''
    }
  }

  stages {
    stage('build') {
      steps {
        container('docker') {
          sh 'ls'
          sh 'echo $CONTAINER_REGISTRY_CREDENTIALS_PSW | docker login --username $CONTAINER_REGISTRY_CREDENTIALS_USR --password-stdin'
          sh 'make ximage VERSION=buildkit'
        }
      }
    }
  }
  
}